"""
Client CSV Migration and Repair Utility for DDoS Research MVP.

Repairs legacy client-side transmission logs:
1. Detects and repairs the 40 legacy misaligned rows where timestamp fell into run_id.
   Assigns them to distinct, reproducible legacy run IDs (legacy_run_01_legit, legacy_run_02_attack_a0,
   legacy_run_03_attack_a5, legacy_run_04_attack_a1) so joins are unambiguous.
2. Identifies and excludes duplicate (run_id, request_id) keys (e.g. repeated test_run_a0 runs)
   so that client-side keys are unique; server-side keys still need auditing.
   Saves excluded duplicate records to a reviewable duplicates log.
3. Supports the repository's original eight-column schema and preserves inter_arrival_ms
   as an actual interval without renaming it to scheduled_interval_ms.
4. Backs up original files before rewriting and validates strict mathematical integrity.
"""

import argparse
import csv
from datetime import datetime
from pathlib import Path
import shutil
import sys
import time

CLIENT_CSV_HEADER = [
    "run_id",
    "request_id",
    "scheduled_time",
    "actual_start_time",
    "mode",
    "alpha",
    "ground_truth",
    "target_url",
    "scheduled_interval_ms",
    "inter_arrival_ms",
    "client_latency_ms",
    "status_code"
]

KNOWN_CLIENT_COLUMNS = set(CLIENT_CSV_HEADER) | {"client_timestamp"}


def is_misaligned_row(row):
    """
    Detects rows from early testing that were shifted into newer column headers:
    - Col 0 is an ISO timestamp string starting with '2026-'
    - Col 2 is 'legitimate' or 'attack' (mode)
    - Col 4 is 'legitimate' or starts with 'attack_alpha_' (ground_truth)
    """
    return (
        len(row) >= 9
        and row[0].startswith("2026-")
        and row[2] in ("legitimate", "attack")
    )


def repair_misaligned_row(row, batch_num):
    """
    Repairs a legacy 9-column row that was shifted into an 11-column template.
    Assigns reproducible legacy run IDs across request-ID reset boundaries.
    """
    mode_label = "legit" if row[2] == "legitimate" else f"attack_a{str(row[3]).replace('.', '')[:2]}"
    run_id = f"legacy_run_{batch_num:02d}_{mode_label}"

    timestamp = row[0]
    request_id = row[1]
    mode = row[2]
    alpha = row[3]
    ground_truth = row[4]
    target_url = row[5]
    # In these 40 rows, row[6] was the scheduled interval generated by the generator
    scheduled_interval_ms = row[6]
    inter_arrival_ms = ""  # Not recorded as actual inter-arrival in 9-col prototype
    client_latency_ms = row[7]
    status_code = row[8] if len(row) > 8 and row[8] else "200"

    return [
        run_id,
        request_id,
        timestamp,  # scheduled_time
        timestamp,  # actual_start_time
        mode,
        alpha,
        ground_truth,
        target_url,
        scheduled_interval_ms,
        inter_arrival_ms,
        client_latency_ms,
        status_code
    ]


def migrate_csv_file(csv_path, duplicates_path=None, backup=True):
    """
    Performs full backed-up migration of client_sent.csv.
    Returns a dictionary of migration statistics.
    """
    csv_path = Path(csv_path)
    if not csv_path.exists():
        raise FileNotFoundError(f"File not found: {csv_path}")

    # Read existing content
    with open(csv_path, mode="r", newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        try:
            current_header = next(reader)
        except StopIteration:
            current_header = []
        raw_rows = list(reader)

    if not current_header:
        with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(CLIENT_CSV_HEADER)
        return {"total_rows": 0, "migrated_rows": 0, "excluded_duplicates": 0, "misaligned_repaired": 0}

    # Reject unknown columns
    unknown_cols = [c for c in current_header if c not in KNOWN_CLIENT_COLUMNS]
    if unknown_cols:
        raise ValueError(f"Unknown CSV schema in {csv_path}: unrecognized columns {unknown_cols}")

    # Create backup before any rewrite
    backup_file = None
    if backup:
        backup_file = csv_path.with_suffix(f".csv.bak_{int(time.time())}")
        shutil.copy2(csv_path, backup_file)

    migrated_rows = []
    misaligned_count = 0
    legacy_batch = 0
    legacy_request_ids = set()
    excluded_duplicates = []
    seen_keys = set()

    is_original_8col = (
        current_header == [
            "client_timestamp", "request_id", "mode", "alpha",
            "target_url", "inter_arrival_ms", "client_latency_ms", "status_code"
        ]
    )

    for idx, row in enumerate(raw_rows):
        if is_misaligned_row(row):
            if row[1] in legacy_request_ids:
                legacy_batch += 1
                legacy_request_ids.clear()
            elif legacy_batch == 0:
                legacy_batch = 1
            legacy_request_ids.add(row[1])
            repaired = repair_misaligned_row(row, legacy_batch)
            misaligned_count += 1
            key = (repaired[0], repaired[1])
            if key in seen_keys:
                excluded_duplicates.append(repaired)
            else:
                seen_keys.add(key)
                migrated_rows.append(repaired)
        elif is_original_8col:
            # Map original 8-column format by column name
            row_dict = dict(zip(current_header, row))
            ts = row_dict.get("client_timestamp", "")
            req_id = row_dict.get("request_id", "")
            if req_id in legacy_request_ids:
                legacy_batch += 1
                legacy_request_ids.clear()
            elif legacy_batch == 0:
                legacy_batch = 1
            legacy_request_ids.add(req_id)
            mode = row_dict.get("mode", "")
            alpha = row_dict.get("alpha", "")
            gt = "legitimate" if mode == "legitimate" else (f"attack_alpha_{float(alpha):.2f}" if alpha else "attack")
            # CRITICAL: Preserve inter_arrival_ms without renaming to scheduled_interval_ms
            repaired = [
                f"legacy_run_original_{legacy_batch:02d}",
                req_id,
                ts,  # scheduled_time
                ts,  # actual_start_time
                mode,
                alpha,
                gt,
                row_dict.get("target_url", ""),
                "",  # scheduled_interval_ms (did not exist in original 8-col)
                row_dict.get("inter_arrival_ms", ""),  # Historical inter_arrival_ms preserved!
                row_dict.get("client_latency_ms", ""),
                row_dict.get("status_code", "")
            ]
            key = (repaired[0], repaired[1])
            if key in seen_keys:
                excluded_duplicates.append(repaired)
            else:
                seen_keys.add(key)
                migrated_rows.append(repaired)
        else:
            # Map dict-based row
            row_dict = dict(zip(current_header, row))
            run_id = row_dict.get("run_id", "")
            req_id = row_dict.get("request_id", "")
            key = (run_id, req_id)

            sched_t = row_dict.get("scheduled_time") or row_dict.get("client_timestamp", "")
            actual_t = row_dict.get("actual_start_time") or row_dict.get("client_timestamp", "")
            mode = row_dict.get("mode", "")
            alpha = row_dict.get("alpha", "")
            gt = row_dict.get("ground_truth", "")
            if not gt and mode:
                gt = "legitimate" if mode == "legitimate" else (f"attack_alpha_{float(alpha):.2f}" if alpha else "attack")

            formatted_row = [
                run_id,
                req_id,
                sched_t,
                actual_t,
                mode,
                alpha,
                gt,
                row_dict.get("target_url", ""),
                row_dict.get("scheduled_interval_ms", ""),
                row_dict.get("inter_arrival_ms", ""),
                row_dict.get("client_latency_ms", ""),
                row_dict.get("status_code", "")
            ]

            if key in seen_keys:
                excluded_duplicates.append(formatted_row)
                continue
            seen_keys.add(key)
            migrated_rows.append(formatted_row)

    # Save excluded duplicates to review file if any exist
    if excluded_duplicates:
        dup_path = Path(duplicates_path) if duplicates_path else csv_path.parent / f"{csv_path.stem}_duplicates.csv"
        with open(dup_path, mode="w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(CLIENT_CSV_HEADER)
            writer.writerows(excluded_duplicates)

    # Write migrated rows
    with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(CLIENT_CSV_HEADER)
        writer.writerows(migrated_rows)

    stats = {
        "original_rows": len(raw_rows),
        "misaligned_repaired": misaligned_count,
        "excluded_duplicates": len(excluded_duplicates),
        "migrated_rows": len(migrated_rows),
        "backup_file": str(backup_file) if backup_file else None,
        "unique_keys": len(seen_keys)
    }

    return stats


def main():
    parser = argparse.ArgumentParser(description="Migrate and repair client CSV log.")
    parser.add_argument("--csv-path", default="data/client_sent.csv", help="Path to client CSV")
    parser.add_argument("--duplicates-path", default=None, help="Path to save excluded duplicates")
    parser.add_argument("--no-backup", action="store_true", help="Skip creating backup")
    args = parser.parse_args()

    target_csv = Path(args.csv_path)
    if not target_csv.is_absolute():
        if not target_csv.exists():
            target_csv = Path(__file__).resolve().parent.parent / args.csv_path

    print("==================================================")
    print("      Client CSV Migration & Repair Tool          ")
    print("==================================================")
    print(f"Target CSV: {target_csv}")
    stats = migrate_csv_file(target_csv, args.duplicates_path, backup=not args.no_backup)
    print(f"Backup Created:        {stats['backup_file']}")
    print(f"Original Rows:         {stats['original_rows']}")
    print(f"Misaligned Repaired:   {stats['misaligned_repaired']}")
    print(f"Excluded Duplicates:   {stats['excluded_duplicates']}")
    print(f"Final Unique Rows:     {stats['migrated_rows']}")
    print("==================================================")
    print("Client migration complete. Audit both logs before a one-to-one join.")


if __name__ == "__main__":
    main()
